# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
