# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-11 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_farmer_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowTractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('from_time', models.CharField(blank=True, max_length=100, null=True)),
                ('to_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LendTractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('from_time', models.CharField(blank=True, max_length=100, null=True)),
                ('to_time', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
