# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-11 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_borrowtractor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LendTractor',
        ),
    ]
