# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-12 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mintemp', models.CharField(blank=True, max_length=100, null=True)),
                ('maxtemp', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
