# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-12 00:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_crop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='crop_name',
            new_name='name',
        ),
    ]
