# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-12 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20171112_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer1', models.CharField(blank=True, max_length=100, null=True)),
                ('farmer2', models.CharField(blank=True, max_length=100, null=True)),
                ('to_date', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('number_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('currently_occupied_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
