# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-12 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_truck'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanding_farmer', models.CharField(blank=True, max_length=100, null=True)),
                ('demand_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('demand_date', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
