# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-11-12 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_farmerdemand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='to_date',
        ),
        migrations.AddField(
            model_name='order',
            name='demand_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='truck',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='occupied',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
